'use strict';
/* GLADION v5.6 — functional Core Forge + Hangar equipment */
(()=>{
const rarityClass=r=>'rarity-'+r.toLowerCase().replaceAll(' ','-');
const rarityRank={NORMAL:0,RARE:1,'SUPER RARE':2,SS:3};
const weights=[['NORMAL',52],['RARE',30],['SUPER RARE',15],['SS',3]];
const owned=id=>saveData.inventory.includes(id);
function syncMoney(){document.querySelectorAll('.coreCount').forEach(e=>e.textContent=saveData.player.cores);document.querySelectorAll('.coinCount').forEach(e=>e.textContent=saveData.player.coins);$('titleCores').textContent=saveData.player.cores;$('forgeFragments').textContent=`${saveData.player.fragments||0} / 20`}
function renderSlots(){const root=$('slots');if(!root)return;root.innerHTML='';for(const slot of CONFIG.slots){const id=saveData.equipped[slot],it=ITEMS.find(x=>x.id===id),el=document.createElement('button');el.type='button';el.className=`slot ${it?rarityClass(it.rarity):''}`;el.dataset.slot=slot;el.innerHTML=`<small>${slot}</small><b>${it?it.name:'EMPTY'}</b>${it?`<em>${it.rarity}</em>`:''}`;root.appendChild(el)}}
function renderInventory(filter=null){const root=$('inventory');if(!root)return;const list=saveData.inventory.map(id=>ITEMS.find(x=>x.id===id)).filter(Boolean).filter(x=>!filter||x.slot===filter).sort((a,b)=>rarityRank[b.rarity]-rarityRank[a.rarity]);root.innerHTML='';for(const it of list){const eq=saveData.equipped[it.slot]===it.id,el=document.createElement('button');el.type='button';el.className=`item-card ${rarityClass(it.rarity)} ${eq?'equipped':''}`;el.dataset.item=it.id;el.innerHTML=`<small>${it.slot} / ${it.rarity}</small><b>${it.name}</b><span>POWER ×${it.power.toFixed(2)}</span><strong>${eq?'EQUIPPED':'装備する'}</strong>`;root.appendChild(el)}$('inventoryCount').textContent=`${list.length} ITEMS`}
function renderHangar(filter=null){syncMoney();renderSlots();renderInventory(filter);$('shipLevel').textContent=saveData.airframe;$('pilotLevel').textContent=`LEVEL ${String(saveData.player.level).padStart(2,'0')}`;$('bestScore').textContent=saveData.best;$('fragments').textContent=`${saveData.player.fragments||0} / 20`;const need=saveData.player.level*100;$('nextXp').textContent=Math.max(0,need-saveData.player.exp);$('pilotXp').style.width=`${clamp(saveData.player.exp/need*100,0,100)}%`}
function equip(id){const it=ITEMS.find(x=>x.id===id);if(!it||!owned(id))return;saveData.equipped[it.slot]=it.id;save();renderHangar(it.slot);toast?.(`${it.name} EQUIPPED`)}
function chooseRarity(){let r=Math.random()*100;for(const [name,w] of weights){r-=w;if(r<0)return name}return'NORMAL'}
function pull(){audio.init();if(saveData.player.cores<3){$('revealType').textContent='CORE不足';$('revealName').textContent='3 CORE REQUIRED';$('revealRarity').textContent='MISSIONでCOREを獲得';$('gachaReveal').className='gacha-reveal';$('gachaReveal').classList.remove('hidden');return}saveData.player.cores-=3;saveData.pity=(saveData.pity||0)+1;let rarity=saveData.pity>=10?'SUPER RARE':chooseRarity();if(saveData.pity>=10&&Math.random()<.18)rarity='SS';if(rarity==='SUPER RARE'||rarity==='SS')saveData.pity=0;let pool=ITEMS.filter(x=>x.rarity===rarity);if(!pool.length)pool=ITEMS;const it=pool[Math.floor(Math.random()*pool.length)],duplicate=owned(it.id);if(duplicate){const bonus=rarity==='SS'?8:rarity==='SUPER RARE'?4:rarity==='RARE'?2:1;saveData.player.fragments=(saveData.player.fragments||0)+bonus;saveData.player.coins+=bonus*120}else saveData.inventory.push(it.id);save();syncMoney();$('revealType').textContent=`${it.slot}${duplicate?' / DUPLICATE':''}`;$('revealName').textContent=it.name;$('revealRarity').textContent=it.rarity+(duplicate?`  +${rarity==='SS'?8:rarity==='SUPER RARE'?4:rarity==='RARE'?2:1} FRAGMENT`:'');const rev=$('gachaReveal');rev.className='gacha-reveal '+(it.rarity==='SS'?'ss':'');rev.classList.remove('hidden');audio.level();renderHangar()}
function upgrade(){const cost=500+(saveData.airframe-1)*250;if(saveData.player.coins<cost){toast?.(`NEED ¢${cost}`);return}saveData.player.coins-=cost;saveData.airframe++;save();renderHangar();toast?.('AIRFRAME UPGRADED')}
function bind(){const slots=$('slots'),inv=$('inventory'),pullBtn=$('pullBtn'),upgradeBtn=$('upgradeShip');slots?.addEventListener('click',e=>{const b=e.target.closest('[data-slot]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();renderHangar(b.dataset.slot)},true);inv?.addEventListener('click',e=>{const b=e.target.closest('[data-item]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();equip(b.dataset.item)},true);pullBtn?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();pull()},true);upgradeBtn?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();upgrade()},true);$('revealClose')?.addEventListener('click',()=>{renderHangar();showOnly('hangarScreen')},true);$('hangarBtn')?.addEventListener('click',()=>setTimeout(()=>renderHangar(),0),true);$('gachaBtn')?.addEventListener('click',()=>setTimeout(syncMoney,0),true);renderHangar()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
window.GLADION_EQUIPMENT={version:'5.6',render:renderHangar};
})();