'use strict';
/* GLADION v6.0 equipment presentation + interaction layer */
(()=>{
const RCOL={NORMAL:'#93a6b8',RARE:'#38bfff','SUPER RARE':'#b85cff',SS:'#ffcc45'};
const SLOTICON={MAIN:'⌁',SUB:'◉',MISSILE:'➤',ARMOR:'⬡',WING:'⌃',ENGINE:'✦',DRONE:'◇',SPECIAL:'✧'};
function color(r){return RCOL[r]||RCOL.NORMAL}
function item(id){return ITEMS.find(x=>x.id===id)}
function svg(it){const c=color(it.rarity),s=it.slot,ic=SLOTICON[s]||'◆',p=Math.round((it.power||1)*100);return `<svg viewBox="0 0 240 120" aria-hidden="true"><defs><linearGradient id="g-${it.id}" x1="0" x2="1"><stop stop-color="${c}" stop-opacity=".08"/><stop offset="1" stop-color="${c}" stop-opacity=".5"/></linearGradient><filter id="b-${it.id}"><feGaussianBlur stdDeviation="5"/></filter></defs><path d="M18 92 L46 32 L118 14 L205 38 L224 76 L170 105 L65 108 Z" fill="url(#g-${it.id})" stroke="${c}" stroke-width="2"/><path d="M42 84 L67 43 L120 29 L188 47 L199 70 L158 91 L76 96 Z" fill="#07111d" stroke="${c}"/><path d="M55 72 H185" stroke="${c}" stroke-width="8" opacity=".2" filter="url(#b-${it.id})"/><text x="120" y="77" text-anchor="middle" fill="${c}" font-size="43" font-family="system-ui" font-weight="800">${ic}</text><text x="16" y="18" fill="${c}" font-size="10" font-family="system-ui" letter-spacing="3">${s} // ${it.rarity}</text><text x="222" y="112" text-anchor="end" fill="#dcecff" font-size="9" font-family="system-ui">OUTPUT ${p}%</text></svg>`}
function card(it,owned=true){const eq=saveData.equipped[it.slot]===it.id,c=color(it.rarity);return `<button class="arsenal-card ${eq?'equipped':''} ${owned?'':'locked'}" data-equip="${it.id}" style="--rarity:${c}" ${owned?'':'disabled'}><div class="gear-art">${svg(it)}</div><div class="gear-meta"><small>${it.slot} / ${it.rarity}</small><b>${it.name}</b><span>POWER ${(it.power||1).toFixed(2)}× ${it.ability?'• '+it.ability.toUpperCase():''}</span></div>${eq?'<em>EQUIPPED</em>':''}</button>`}
function refresh(){if(!window.saveData||!window.ITEMS)return;document.querySelectorAll('.coreCount').forEach(e=>e.textContent=saveData.player.cores);document.querySelectorAll('.coinCount').forEach(e=>e.textContent=saveData.player.coins);const inv=document.getElementById('inventory');if(inv){const owned=[...new Set(saveData.inventory)].map(item).filter(Boolean);inv.innerHTML=owned.map(x=>card(x)).join('');const cnt=document.getElementById('inventoryCount');if(cnt)cnt.textContent=`${owned.length} ITEMS`;inv.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>equip(b.dataset.equip))}const slots=document.getElementById('slots');if(slots){slots.innerHTML=CONFIG.slots.map(slot=>{const it=item(saveData.equipped[slot]);const c=it?color(it.rarity):'#31465a';return `<button class="slot-v6" data-slot="${slot}" style="--rarity:${c}"><small>${slot}</small>${it?`<div>${svg(it)}</div><b>${it.name}</b><span>${it.rarity}</span>`:'<div class="empty-gear">＋</div><b>EMPTY</b><span>SELECT EQUIPMENT</span>'}</button>`}).join('');slots.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>picker(b.dataset.slot))}const frag=document.getElementById('fragments');if(frag)frag.textContent=`${saveData.player.fragments||0} / 20`;const ff=document.getElementById('forgeFragments');if(ff)ff.textContent=`${saveData.player.fragments||0} / 20`}
function equip(id){const it=item(id);if(!it||!saveData.inventory.includes(id))return;saveData.equipped[it.slot]=id;save();refresh();toast?.(`${it.name} EQUIPPED`)}
function picker(slot){const owned=[...new Set(saveData.inventory)].map(item).filter(x=>x&&x.slot===slot);let modal=document.getElementById('gearPicker');if(!modal){modal=document.createElement('div');modal.id='gearPicker';modal.className='gear-picker';document.body.appendChild(modal)}modal.innerHTML=`<div class="gear-picker-panel"><header><div><small>LOADOUT / ${slot}</small><h2>SELECT EQUIPMENT</h2></div><button id="gearPickerClose">×</button></header><div class="gear-picker-list">${owned.length?owned.map(x=>card(x)).join(''):'<p class="no-gear">このスロットの装備をまだ所持していません。<br>CORE FORGEで解析してください。</p>'}</div></div>`;modal.classList.add('open');modal.querySelector('#gearPickerClose').onclick=()=>modal.classList.remove('open');modal.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{equip(b.dataset.equip);modal.classList.remove('open')})}
function revealGraphic(){const r=document.getElementById('gachaReveal');if(!r)return;const obs=new MutationObserver(()=>{if(r.classList.contains('hidden'))return;const name=document.getElementById('revealName')?.textContent;const it=ITEMS.find(x=>x.name===name);if(!it)return;let art=r.querySelector('.reveal-gear-art');if(!art){art=document.createElement('div');art.className='reveal-gear-art';r.insertBefore(art,document.getElementById('revealType'))}art.innerHTML=svg(it);r.style.setProperty('--rarity',color(it.rarity))});obs.observe(r,{attributes:true,attributeFilter:['class'],subtree:true,childList:true})}
const oldRender=window.renderHangar;window.renderHangar=function(){if(oldRender)oldRender();refresh()};
document.addEventListener('click',e=>{if(e.target.closest('#hangarBtn'))setTimeout(refresh,0)});
revealGraphic();setTimeout(refresh,0);window.GLADION_EQUIPMENT_UI='6.0';
})();