'use strict';
/* GLADION v1.0 — dependency-free, data-driven canvas shooter */
const $=id=>document.getElementById(id), clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), rand=(a,b)=>a+Math.random()*(b-a), dist2=(a,b)=>{const x=a.x-b.x,y=a.y-b.y;return x*x+y*y};
const CONFIG={stageLength:78,bossAt:61,maxParticles:520,saveKey:'gladion.save.v1',version:1,slots:['MAIN','SUB','MISSILE','ARMOR','WING','ENGINE','DRONE','SPECIAL']};
const ITEMS=[
 {id:'pulse-mk1',slot:'MAIN',name:'PULSE Mk-I',rarity:'NORMAL',power:1},{id:'razor',slot:'MAIN',name:'RAZOR CANNON',rarity:'RARE',power:1.18},{id:'seraph',slot:'MAIN',name:'SERAPH SPLITTER',rarity:'SS',power:1.48,ability:'split'},
 {id:'beam',slot:'SUB',name:'AZURE BEAM',rarity:'RARE',power:1.1},{id:'nova',slot:'SUB',name:'NOVA LANCER',rarity:'SUPER RARE',power:1.3},{id:'hydra',slot:'MISSILE',name:'HYDRA SWARM',rarity:'SS',power:1.5,ability:'multilock'},
 {id:'falcon',slot:'MISSILE',name:'FALCON-2',rarity:'NORMAL',power:1},{id:'aegis',slot:'ARMOR',name:'AEGIS PLATE',rarity:'RARE',power:1.2},{id:'blackarmor',slot:'ARMOR',name:'BLACK MIRROR',rarity:'SS',power:1.5,ability:'barrier'},
 {id:'wing',slot:'WING',name:'VECTOR WING',rarity:'NORMAL',power:1},{id:'redwing',slot:'WING',name:'CRIMSON WING',rarity:'SUPER RARE',power:1.25},{id:'engine',slot:'ENGINE',name:'ION ENGINE',rarity:'NORMAL',power:1},
 {id:'drone',slot:'DRONE',name:'BIT DRONE',rarity:'SUPER RARE',power:1.25,ability:'option'},{id:'void',slot:'SPECIAL',name:'VOID BREAKER',rarity:'SS',power:1.5,ability:'nova'}];
const DEFAULT={version:1,player:{level:1,exp:0,coins:1200,cores:9,fragments:0},airframe:1,stage:1,best:0,pity:0,inventory:['pulse-mk1','falcon','aegis','wing','engine'],equipped:{MAIN:'pulse-mk1',MISSILE:'falcon',ARMOR:'aegis',WING:'wing',ENGINE:'engine'},weaponLevels:{MAIN:1,SUB:1,MISSILE:1},settings:{sound:true,shake:true},updatedAt:0};
const clone=value=>typeof structuredClone==='function'?structuredClone(value):JSON.parse(JSON.stringify(value));
function load(){try{let raw=JSON.parse(localStorage.getItem(CONFIG.saveKey));if(!raw){const legacy=JSON.parse(localStorage.getItem('gladion'));if(legacy){raw={player:{level:legacy.lv,exp:legacy.xp,coins:legacy.coins,cores:legacy.cores},best:legacy.best,weaponLevels:{MAIN:legacy.weapon}}}}if(!raw)return clone(DEFAULT);return {...clone(DEFAULT),...raw,version:CONFIG.version,player:{...DEFAULT.player,...(raw.player||{})},equipped:{...DEFAULT.equipped,...(raw.equipped||{})},weaponLevels:{...DEFAULT.weaponLevels,...(raw.weaponLevels||{})},settings:{...DEFAULT.settings,...(raw.settings||{})},inventory:Array.isArray(raw.inventory)?raw.inventory:clone(DEFAULT.inventory)}}catch(e){console.warn('Save recovered',e);return clone(DEFAULT)}}
let saveData=load(); function save(){saveData.updatedAt=Date.now();localStorage.setItem(CONFIG.saveKey,JSON.stringify(saveData))}
class AudioEngine{constructor(){this.ctx=null} init(){if(!this.ctx)try{const AudioContextClass=globalThis.AudioContext||globalThis.webkitAudioContext;if(AudioContextClass)this.ctx=new AudioContextClass()}catch(e){console.warn('Audio unavailable',e)}this.ctx?.resume()} tone(freq=.5,dur=.08,type='sawtooth',gain=.035,slide=0){if(!saveData.settings.sound||!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),now=this.ctx.currentTime;o.type=type;o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(Math.max(25,freq+slide),now+dur);g.gain.setValueAtTime(gain,now);g.gain.exponentialRampToValueAtTime(.0001,now+dur);o.connect(g).connect(this.ctx.destination);o.start();o.stop(now+dur)} shot(){this.tone(520,.035,'square',.018,-190)} hit(){this.tone(180,.045,'square',.025,-80)} explosion(big=false){this.tone(big?90:140,big?.5:.16,'sawtooth',big?.09:.045,-55)} item(){this.tone(650,.18,'sine',.05,620)} level(){[440,660,990].forEach((f,i)=>setTimeout(()=>this.tone(f,.18,'sine',.05,100),i*90))} warning(){this.tone(115,.35,'square',.07,-20)}}
const audio=new AudioEngine();
class Pool{constructor(factory,cap){this.items=Array.from({length:cap},factory)} get(data){const o=this.items.find(x=>!x.active);if(o){Object.assign(o,data,{active:true});return o}} each(fn){for(const o of this.items)if(o.active)fn(o)} clear(){this.items.forEach(o=>o.active=false)}}
const canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false}); let W=1280,H=720,DPR=1;
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)} addEventListener('resize',resize);resize();
const bullets=new Pool(()=>({active:false}),280),enemyBullets=new Pool(()=>({active:false}),180),particles=new Pool(()=>({active:false}),CONFIG.maxParticles),missiles=new Pool(()=>({active:false}),50),drops=new Pool(()=>({active:false}),35);
let enemies=[],player={},G={mode:'title',time:0,last:0,elapsed:0,spawn:0,score:0,kills:0,combo:0,comboTime:0,shake:0,flash:0,slow:1,boss:null,bossTriggered:false,clearing:false,drag:false};
function equipped(slot){return ITEMS.find(i=>i.id===saveData.equipped[slot])}
function resetPlayer(){const armor=equipped('ARMOR');player={x:W*.17,y:H*.5,targetX:W*.17,targetY:H*.5,r:13,hp:100+(saveData.airframe-1)*5,maxHp:100+(saveData.airframe-1)*5,shield:armor?.ability==='barrier'?90:50,maxShield:armor?.ability==='barrier'?90:50,shot:1,laser:0,missile:0,fire:0,laserTick:0,missileTick:0,invuln:1.8,rapid:0,drones:equipped('DRONE')?1:0,od:0,overdrive:0};}
function startGame(){audio.init();bullets.clear();enemyBullets.clear();particles.clear();missiles.clear();drops.clear();enemies=[];resetPlayer();Object.assign(G,{mode:'play',time:0,last:performance.now(),elapsed:0,spawn:.8,score:0,kills:0,combo:0,comboTime:0,shake:0,flash:0,slow:1,boss:null,bossTriggered:false,clearing:false});showOnly(null);$('combatHud').classList.remove('hidden');$('bossBar').classList.add('hidden');$('bossTitle').textContent='DARK OCEAN FRONT';requestAnimationFrame(loop)}
function showOnly(id){['titleScreen','hangarScreen','forgeScreen','pauseScreen','resultScreen'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}
function particle(x,y,color='#ff5838',count=8,speed=180,size=3){for(let i=0;i<count;i++){const a=Math.random()*7,s=rand(speed*.25,speed);particles.get({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.18,.65),max:.65,size:rand(1,size),color,drag:.95})}}
function explosion(x,y,big=false){particle(x,y,'#ff3c22',big?45:13,big?420:210,big?8:4);particle(x,y,'#ffd77a',big?25:7,big?300:150,big?5:3);G.shake=Math.max(G.shake,big?18:5);G.flash=big?.35:.08;audio.explosion(big)}
const ENEMY={scout:{hp:3,speed:115,r:15,score:100,color:'#da263c',move:(e,dt)=>{e.x-=e.speed*dt;e.y+=Math.sin(G.time*4+e.seed)*35*dt},fire:2.2},dart:{hp:2,speed:230,r:11,score:140,color:'#ff8847',move:(e,dt)=>{e.x-=e.speed*dt;e.y+=Math.sin(G.time*7+e.seed)*90*dt},fire:9},armor:{hp:16,speed:55,r:25,score:350,color:'#8e3243',move:(e,dt)=>{e.x-=e.speed*dt;e.y+=Math.sin(G.time+e.seed)*12*dt},fire:1.35},bomber:{hp:9,speed:70,r:21,score:280,color:'#8141aa',move:(e,dt)=>{e.x-=e.speed*dt;e.y+=Math.cos(G.time*2+e.seed)*26*dt},fire:.8},drone:{hp:4,speed:100,r:13,score:180,color:'#2c92c9',move:(e,dt)=>{e.x-=e.speed*dt;e.y+=Math.sin(G.time*5+e.seed)*55*dt},fire:1.7}};
function spawnEnemy(type=null,y=null){type=type||(['scout','scout','dart','armor','bomber','drone'][Math.floor(Math.random()*6)]);const d=ENEMY[type],scale=1+G.elapsed/100;enemies.push({type,x:W+35,y:y??rand(65,H-60),hp:d.hp*scale,maxHp:d.hp*scale,speed:d.speed,r:d.r,score:d.score,color:d.color,fire:rand(.4,d.fire),seed:Math.random()*10,dead:false})}
function spawnBoss(){audio.warning();toast('WARNING');G.bossTriggered=true;setTimeout(()=>{if(G.mode!=='play')return;const b={type:'boss',x:W+180,y:H*.5,hp:1250,maxHp:1250,r:92,phase:1,fire:1,burst:0,dead:false,score:12000,color:'#a51930'};enemies.push(b);G.boss=b;$('bossBar').classList.remove('hidden');$('bossTitle').textContent='ABYSSAL DREADNOUGHT';},1800)}
function enemyFire(e){if(e.x>W-20)return;const a=Math.atan2(player.y-e.y,player.x-e.x),speed=e.type==='boss'?190:130;enemyBullets.get({x:e.x-e.r*.6,y:e.y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:e.type==='boss'?5:3,life:7,color:e.type==='boss'?'#ff3752':'#ff9b45'});if(e.type==='bomber'){for(const off of [-.25,.25])enemyBullets.get({x:e.x,y:e.y,vx:Math.cos(a+off)*speed,vy:Math.sin(a+off)*speed,r:4,life:7,color:'#c74cff'})}audio.tone(125,.07,'square',.012,-30)}
function firePlayer(){const ways=[1,2,3,5,7][player.shot-1],power=(equipped('MAIN')?.power||1)*(player.overdrive?1.8:1);for(let i=0;i<ways;i++){const spread=(i-(ways-1)/2)*.055;bullets.get({x:player.x+30,y:player.y+spread*65,vx:650,vy:spread*650,r:3,damage:1.3*power,life:2,color:'#66dcff'})}if(player.drones)bullets.get({x:player.x,y:player.y-35,vx:620,vy:0,r:4,damage:1.2*power,life:2,color:'#ffd057'});audio.shot()}
function fireMissile(){const n=Math.min(player.missile+(player.missile===5?3:0),8);for(let i=0;i<n;i++)missiles.get({x:player.x,y:player.y+(i%2?16:-16),vx:170,vy:(i-n/2)*18,r:5,damage:(3+player.missile*1.6)*(equipped('MISSILE')?.power||1),life:5,trail:0})}
function damageEnemy(e,dmg,x,y){if(e.dead)return;e.hp-=dmg;particle(x,y,'#ecfaff',2,70,2);audio.hit();if(e.hp<=0)killEnemy(e)}
function killEnemy(e){if(e.dead)return;e.dead=true;G.score+=e.score;G.kills++;G.combo++;G.comboTime=2.2;player.od=clamp(player.od+(e.type==='boss'?100:7),0,100);explosion(e.x,e.y,e.type==='boss');if(e.type==='boss'){bossDeath(e);return}gainExp(8+Math.round(e.maxHp));if(Math.random()<.32)spawnDrop(e.x,e.y);if(G.combo%10===0)toast(`${G.combo} CHAIN`)}
function spawnDrop(x,y){const r=Math.random(),type=r<.28?'SHOT':r<.48?'LASER':r<.67?'MISSILE':r<.78?'SHIELD':r<.87?'REPAIR':r<.94?'RAPID':r<.98?'NOVA':'CORE';drops.get({x,y,vx:-65,vy:rand(-20,20),type,r:11,life:10,spin:0})}
function collect(d){d.active=false;audio.item();const map={SHOT:()=>player.shot=Math.min(5,player.shot+1),LASER:()=>player.laser=Math.min(5,player.laser+1),MISSILE:()=>player.missile=Math.min(5,player.missile+1),SHIELD:()=>player.shield=Math.min(player.maxShield,player.shield+35),REPAIR:()=>player.hp=Math.min(player.maxHp,player.hp+30),RAPID:()=>player.rapid=10,NOVA:()=>{enemies.filter(e=>e.type!=='boss').forEach(e=>damageEnemy(e,99,e.x,e.y));G.flash=.3},CORE:()=>{saveData.player.cores++;save()}};map[d.type]();toast(d.type==='NOVA'?'ALL RANGE BURST':`${d.type} POWER UP`)}
function gainExp(n){saveData.player.exp+=n;let need=saveData.player.level*100;if(saveData.player.exp>=need){saveData.player.exp-=need;saveData.player.level++;saveData.player.cores++;player.hp=player.maxHp;audio.level();toast('LEVEL UP');particle(player.x,player.y,'#6eeaff',35,260,5)}save()}
function hitPlayer(dmg){if(player.invuln>0||G.mode!=='play')return;if(player.shield>0){const used=Math.min(player.shield,dmg);player.shield-=used;dmg-=used}player.hp-=dmg;player.invuln=1;G.shake=12;G.flash=.15;particle(player.x,player.y,'#62ddff',18,220,4);if(player.hp<=0)endMission(false)}
function bossDeath(e){G.clearing=true;G.slow=.25;let i=0;const timer=setInterval(()=>{explosion(e.x+rand(-75,75),e.y+rand(-65,65),i===6);i++;if(i>6){clearInterval(timer);e.active=false;saveData.player.coins+=1800;saveData.player.cores+=3;saveData.stage=Math.max(saveData.stage,2);gainExp(400);save();setTimeout(()=>endMission(true),700)}},220)}
function endMission(win){if(G.mode==='result')return;G.mode='result';saveData.best=Math.max(saveData.best,G.score);if(!win)saveData.player.coins+=Math.floor(G.score/40);save();$('combatHud').classList.add('hidden');$('resultKicker').textContent=win?'OPERATION COMPLETE':'TACTICAL LINK LOST';$('resultTitle').textContent=win?'MISSION CLEAR':'MISSION FAILED';$('resultStats').innerHTML=`<span>SCORE<b>${G.score.toLocaleString()}</b></span><span>DESTROYED<b>${G.kills}</b></span><span>EXP<b>+${win?400:G.kills*8}</b></span><span>REWARD<b>¢ ${win?1800:Math.floor(G.score/40)}</b></span>`;showOnly('resultScreen')}
function activateOD(){if(player.od<100||player.overdrive)return;player.od=0;player.overdrive=8;player.invuln=1;audio.level();toast('OVERDRIVE');particle(player.x,player.y,'#8deaff',50,310,5)}
function update(dt){G.time+=dt;G.elapsed+=dt;G.spawn-=dt;G.comboTime-=dt;if(G.comboTime<=0)G.combo=0;player.invuln-=dt;player.rapid-=dt;player.overdrive-=dt;player.x+=(player.targetX-player.x)*Math.min(1,dt*13*(player.overdrive?1.5:1));player.y+=(player.targetY-player.y)*Math.min(1,dt*13*(player.overdrive?1.5:1));player.x=clamp(player.x,38,W*.68);player.y=clamp(player.y,48,H-38);player.fire-=dt;if(player.fire<=0){firePlayer();player.fire=player.overdrive?.055:player.rapid>0?.075:.115}if(player.laser){player.laserTick-=dt;if(player.laserTick<=0)player.laserTick=.8-player.laser*.07}if(player.missile){player.missileTick-=dt;if(player.missileTick<=0){fireMissile();player.missileTick=Math.max(.7,2.4-player.missile*.24)}}if(!G.bossTriggered&&G.elapsed>=CONFIG.bossAt)spawnBoss();if(!G.bossTriggered&&G.spawn<=0){spawnEnemy();if(Math.random()<.22)spawnEnemy('scout');G.spawn=Math.max(.38,1.05-G.elapsed*.008)}
 bullets.each(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||b.x>W+30)b.active=false;for(const e of enemies)if(!e.dead&&b.active&&dist2(b,e)<(b.r+e.r)**2){damageEnemy(e,b.damage,b.x,b.y);b.active=false}});
 missiles.each(m=>{let target=enemies.filter(e=>!e.dead).sort((a,b)=>dist2(m,a)-dist2(m,b))[0];if(target){const a=Math.atan2(target.y-m.y,target.x-m.x);m.vx+=(Math.cos(a)*310-m.vx)*dt*3;m.vy+=(Math.sin(a)*310-m.vy)*dt*3}m.x+=m.vx*dt;m.y+=m.vy*dt;m.life-=dt;m.trail-=dt;if(m.trail<=0){particle(m.x-5,m.y,'#b8d9df',1,35,4);m.trail=.035}if(m.life<0)m.active=false;for(const e of enemies)if(!e.dead&&m.active&&dist2(m,e)<(m.r+e.r)**2){damageEnemy(e,m.damage,m.x,m.y);explosion(m.x,m.y);m.active=false}});
 enemyBullets.each(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<0||b.x<-20)b.active=false;if(b.active&&dist2(b,player)<(b.r+player.r)**2){b.active=false;hitPlayer(9)}});
 particles.each(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=p.drag;p.vy*=p.drag;p.life-=dt;if(p.life<0)p.active=false});drops.each(d=>{d.x+=d.vx*dt;d.y+=d.vy*dt;d.spin+=dt*4;d.life-=dt;if(d.life<0)d.active=false;if(d.active&&dist2(d,player)<(d.r+player.r+8)**2)collect(d)});
 for(const e of enemies){if(e.dead)continue;if(e.type==='boss'){e.x+=(W*.78-e.x)*dt*.7;e.y=H*.5+Math.sin(G.time*.8)*H*.17;e.phase=e.hp/e.maxHp<.28?4:e.hp/e.maxHp<.52?3:e.hp/e.maxHp<.76?2:1;e.fire-=dt;if(e.fire<=0){const shots=2+e.phase*2;for(let i=0;i<shots;i++){const a=Math.PI+(i-(shots-1)/2)*.13;enemyBullets.get({x:e.x-60,y:e.y,vx:Math.cos(a)*rand(150,230),vy:Math.sin(a)*190,r:4+(e.phase>2),life:7,color:e.phase===4?'#ffdf5e':'#ff314d'})}e.fire=Math.max(.25,1-e.phase*.14);audio.tone(80,.1,'sawtooth',.025,-25)}}else ENEMY[e.type].move(e,dt);e.fire-=dt;if(e.fire<=0){enemyFire(e);e.fire=ENEMY[e.type]?.fire||1}if(e.x<-50)e.dead=true;if(!e.dead&&dist2(e,player)<(e.r+player.r)**2){hitPlayer(e.type==='boss'?35:18);if(e.type!=='boss')killEnemy(e)}}enemies=enemies.filter(e=>!e.dead||e.type==='boss'&&G.clearing);
 if(player.laser&&player.laserTick>.58-player.laser*.04){for(const e of enemies)if(!e.dead&&Math.abs(e.y-player.y)<7+player.laser*3&&e.x>player.x)damageEnemy(e,dt*(15+player.laser*6)*(equipped('SUB')?.power||1),e.x,e.y)}
 G.shake*=.88;G.flash=Math.max(0,G.flash-dt);if(G.slow<1)G.slow=Math.min(1,G.slow+dt*.15);updateHud()}
function bg(){const t=G.time;let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#030711');g.addColorStop(.5,'#0a1d30');g.addColorStop(1,'#03101a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#24465d';for(let i=0;i<45;i++){let x=(i*257-t*12)% (W+200);if(x<0)x+=W+200;ctx.globalAlpha=.2+(i%3)*.12;ctx.fillRect(x,(i*83)%Math.max(100,H*.55),i%4?1:2,i%4?1:2)}ctx.globalAlpha=1;ctx.fillStyle='#071523';ctx.beginPath();ctx.moveTo(0,H*.65);for(let x=0;x<=W;x+=70)ctx.lineTo(x,H*.58+Math.sin(x*.013+t*.12)*35);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();ctx.fillStyle='#0c2b3d';for(let i=0;i<12;i++){let x=(i*180-t*24)%(W+250);if(x<-100)x+=W+250;ctx.fillRect(x,H*.55-(i%4)*18,90,H*.3);ctx.fillStyle='#de263844';ctx.fillRect(x+15,H*.58-(i%4)*18,2,18);ctx.fillStyle='#0c2b3d'}ctx.fillStyle='#06101a';ctx.fillRect(0,H*.78,W,H*.22);ctx.strokeStyle='#1c5a7466';ctx.lineWidth=1;for(let i=0;i<10;i++){let y=H*.8+i*18+Math.sin(t+i)*2;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle='#03080e';for(let i=0;i<6;i++){let x=(i*310-t*105)%(W+400);if(x<-200)x+=W+400;ctx.fillRect(x,H*.87,210,H*.13);ctx.fillRect(x+35,H*.8,8,H*.2)}}
function drawShip(c,x,y,s=1){c.save();c.translate(x,y);c.scale(s,s);c.shadowBlur=20;c.shadowColor=player.overdrive?'#74eaff':'#e51d3b';c.fillStyle='#ea263e';c.fillRect(-32,-6,25,12);c.shadowBlur=0;c.fillStyle='#344759';c.beginPath();c.moveTo(-22,0);c.lineTo(-7,-25);c.lineTo(12,-14);c.lineTo(37,0);c.lineTo(12,14);c.lineTo(-7,25);c.closePath();c.fill();c.strokeStyle='#9bb4c6';c.lineWidth=2;c.stroke();c.fillStyle='#d8e5ed';c.beginPath();c.moveTo(38,0);c.lineTo(3,-8);c.lineTo(-9,0);c.lineTo(3,8);c.closePath();c.fill();c.fillStyle='#1e9ec9';c.fillRect(2,-4,16,8);c.fillStyle='#dd223b';c.fillRect(-9,-18,4,36);c.restore()}
function draw(){ctx.save();if(G.shake){ctx.translate(rand(-G.shake,G.shake),rand(-G.shake,G.shake))}bg();drops.each(d=>{ctx.save();ctx.translate(d.x,d.y);ctx.rotate(d.spin);ctx.shadowBlur=14;ctx.shadowColor=d.type==='CORE'?'#ffd657':'#45cfff';ctx.fillStyle=d.type==='CORE'?'#ffd657':'#58cfee';ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,r=i%2?7:12;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.fill();ctx.fillStyle='#07101a';ctx.font='bold 7px sans-serif';ctx.textAlign='center';ctx.fillText(d.type[0],0,3);ctx.restore()});
 bullets.each(b=>{ctx.shadowBlur=10;ctx.shadowColor=b.color;ctx.fillStyle='#e8fbff';ctx.fillRect(b.x-3,b.y-1,b.r*3,2)});missiles.each(m=>{ctx.fillStyle='#dfe8ec';ctx.fillRect(m.x-6,m.y-2,12,4);ctx.fillStyle='#ff4930';ctx.fillRect(m.x-9,m.y-1,4,2)});enemyBullets.each(b=>{ctx.shadowBlur=12;ctx.shadowColor=b.color;ctx.fillStyle=b.color;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill()});ctx.shadowBlur=0;
 for(const e of enemies)drawEnemy(e);if(player.overdrive>0){ctx.strokeStyle='#6feaff88';ctx.lineWidth=2;for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(player.x,player.y,25+i*9+Math.sin(G.time*9+i)*4,0,7);ctx.stroke()}}if(player.laser&&player.laserTick>.58-player.laser*.04){ctx.strokeStyle='#72eaff';ctx.shadowColor='#28bfff';ctx.shadowBlur=18;ctx.lineWidth=2+player.laser*2;ctx.beginPath();ctx.moveTo(player.x+30,player.y);ctx.lineTo(W,player.y);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(1,player.laser*.6);ctx.stroke();ctx.shadowBlur=0}if(player.invuln<=0||Math.floor(G.time*16)%2)drawShip(ctx,player.x,player.y,.85);if(player.drones){ctx.fillStyle='#ffd75e';ctx.beginPath();ctx.arc(player.x-2,player.y-34,5,0,7);ctx.fill()}particles.each(p=>{ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x-p.size/2,p.y-p.size/2,p.size,p.size)});ctx.globalAlpha=1;ctx.restore();if(G.flash){ctx.fillStyle=`rgba(255,255,255,${G.flash})`;ctx.fillRect(0,0,W,H)}}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);if(e.type==='boss'){ctx.shadowBlur=28;ctx.shadowColor='#c31d35';ctx.fillStyle='#202c37';ctx.beginPath();ctx.moveTo(85,0);ctx.lineTo(42,-75);ctx.lineTo(-60,-90);ctx.lineTo(-92,-45);ctx.lineTo(-108,0);ctx.lineTo(-92,45);ctx.lineTo(-60,90);ctx.lineTo(42,75);ctx.closePath();ctx.fill();ctx.strokeStyle='#7d91a0';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle=e.phase>=3?'#ffb42e':'#e51e3c';for(const y of [-48,0,48])ctx.fillRect(-75,y-5,55,10);ctx.fillStyle='#080c12';ctx.fillRect(10,-55,55,110);ctx.strokeStyle='#e92a42';ctx.strokeRect(10,-55,55,110);if(e.phase>=2){ctx.fillStyle='#a8bdca';ctx.fillRect(-10,-85,65,14);ctx.fillRect(-10,71,65,14)}}else{ctx.shadowBlur=12;ctx.shadowColor=e.color;ctx.fillStyle='#26333e';ctx.beginPath();ctx.moveTo(-e.r,0);ctx.lineTo(e.r,-e.r*.55);ctx.lineTo(e.r*.55,0);ctx.lineTo(e.r,e.r*.55);ctx.closePath();ctx.fill();ctx.strokeStyle=e.color;ctx.lineWidth=3;ctx.stroke();ctx.fillStyle=e.color;ctx.fillRect(-e.r*.6,-3,e.r*1.1,6)}ctx.restore()}
function updateHud(){$('hpBar').style.width=`${clamp(player.hp/player.maxHp*100,0,100)}%`;$('shieldBar').style.width=`${clamp(player.shield/player.maxShield*100,0,100)}%`;$('hpText').textContent=Math.ceil(Math.max(0,player.hp));$('shieldText').textContent=Math.ceil(Math.max(0,player.shield));$('scoreText').textContent=String(G.score).padStart(8,'0');$('comboText').textContent=`× ${G.combo}`;$('levelText').textContent=String(saveData.player.level).padStart(2,'0');$('expBar').style.width=`${saveData.player.exp/(saveData.player.level*100)*100}%`;$('odBar').style.width=`${player.od}%`;$('overdriveBtn').disabled=player.od<100;$('overdriveBtn').classList.toggle('ready',player.od>=100);$('shotLevel').textContent=['Ⅰ','Ⅱ','Ⅲ','Ⅳ','MAX'][player.shot-1];$('laserLevel').textContent=player.laser?['Ⅰ','Ⅱ','Ⅲ','Ⅳ','MAX'][player.laser-1]:'—';$('missileLevel').textContent=player.missile?['Ⅰ','Ⅱ','Ⅲ','Ⅳ','MAX'][player.missile-1]:'—';if(G.boss)$('bossBar').firstElementChild.style.width=`${clamp(G.boss.hp/G.boss.maxHp*100,0,100)}%`}
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.remove('hidden');e.style.animation='none';void e.offsetWidth;e.style.animation='';setTimeout(()=>e.classList.add('hidden'),950)}
function loop(now){if(G.mode!=='play')return;const dt=Math.min(.033,(now-G.last)/1000||.016)*G.slow;G.last=now;update(dt);draw();requestAnimationFrame(loop)}
function pointer(e){if(G.mode!=='play')return;const p=e.touches?.[0]||e;player.targetX=p.clientX;player.targetY=p.clientY}canvas.addEventListener('pointerdown',e=>{e.preventDefault();G.drag=true;canvas.setPointerCapture?.(e.pointerId);pointer(e)});addEventListener('pointermove',e=>{if(G.drag)pointer(e)});addEventListener('pointerup',()=>G.drag=false);addEventListener('pointercancel',()=>G.drag=false);canvas.addEventListener('touchmove',e=>{e.preventDefault();pointer(e)},{passive:false});addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});addEventListener('dblclick',e=>e.preventDefault(),{passive:false});
function refreshMeta(){$('titleLevel').textContent=`LV.${String(saveData.player.level).padStart(2,'0')}`;$('titleCores').textContent=saveData.player.cores;document.querySelectorAll('.coreCount').forEach(e=>e.textContent=saveData.player.cores);document.querySelectorAll('.coinCount').forEach(e=>e.textContent=saveData.player.coins)}
function rarityClass(r){return 'rarity-'+r.toLowerCase().replaceAll(' ','-')}
function renderHangar(){refreshMeta();$('shipLevel').textContent=saveData.airframe;$('pilotLevel').textContent=`LEVEL ${String(saveData.player.level).padStart(2,'0')}`;$('pilotXp').style.width=`${saveData.player.exp/(saveData.player.level*100)*100}%`;$('nextXp').textContent=saveData.player.level*100-saveData.player.exp;$('bestScore').textContent=saveData.best.toLocaleString();$('fragments').textContent=`${saveData.player.fragments} / 20`;$('inventoryCount').textContent=`${saveData.inventory.length} ITEMS`;$('slots').innerHTML=CONFIG.slots.map(slot=>{const item=equipped(slot);return `<div class="slot ${item?rarityClass(item.rarity):''}"><small>${slot}</small><b>${item?.name||'EMPTY'}</b></div>`}).join('');$('inventory').innerHTML=saveData.inventory.map((id,i)=>{const item=ITEMS.find(x=>x.id===id);if(!item)return'';return `<button class="item-card ${rarityClass(item.rarity)} ${saveData.equipped[item.slot]===id?'equipped':''}" data-item="${id}"><small>${item.slot} / ${item.rarity}</small><b>${item.name}</b></button>`}).join('');document.querySelectorAll('[data-item]').forEach(el=>el.onclick=()=>{const item=ITEMS.find(x=>x.id===el.dataset.item);saveData.equipped[item.slot]=item.id;save();renderHangar();drawPreview()});drawPreview()}
function drawPreview(){const c=$('shipPreview'),q=c.getContext('2d');q.clearRect(0,0,c.width,c.height);q.strokeStyle='#1d536c';q.globalAlpha=.5;for(let r=30;r<200;r+=35){q.beginPath();q.ellipse(280,190,r*1.5,r*.55,0,0,7);q.stroke()}q.globalAlpha=1;const old=player;player={overdrive:0};drawShip(q,280,175,2.8);player=old}
function pullGacha(){audio.init();if(saveData.player.cores<3){$('pullBtn').textContent='COREが不足しています';setTimeout(()=>$('pullBtn').textContent='◈ 3 CORE　解析開始',1200);return}saveData.player.cores-=3;saveData.pity++;let r=Math.random(),rarity=saveData.pity>=10?'SUPER RARE':r<.04?'SS':r<.18?'SUPER RARE':r<.45?'RARE':'NORMAL';if(['SS','SUPER RARE'].includes(rarity))saveData.pity=0;let pool=ITEMS.filter(i=>i.rarity===rarity);if(!pool.length)pool=ITEMS;const item=pool[Math.floor(Math.random()*pool.length)];if(!saveData.inventory.includes(item.id))saveData.inventory.push(item.id);else{saveData.player.fragments+=rarity==='SS'?5:rarity==='SUPER RARE'?2:1;saveData.player.coins+=rarity==='NORMAL'?250:500}if(rarity==='SS')saveData.player.fragments+=3;save();refreshMeta();$('forgeFragments').textContent=`${saveData.player.fragments} / 20`;$('revealType').textContent=item.slot;$('revealName').textContent=item.name;$('revealRarity').textContent=rarity;$('gachaReveal').className=`gacha-reveal ${rarityClass(rarity)} ${rarity==='SS'?'ss':''}`;audio.warning();setTimeout(()=>rarity==='SS'&&audio.level(),400)}
$('startBtn').onclick=startGame;$('hangarBtn').onclick=()=>{showOnly('hangarScreen');renderHangar()};$('gachaBtn').onclick=()=>{showOnly('forgeScreen');refreshMeta();$('forgeFragments').textContent=`${saveData.player.fragments} / 20`};document.querySelectorAll('.backBtn').forEach(b=>b.onclick=()=>{showOnly('titleScreen');refreshMeta()});$('pullBtn').onclick=pullGacha;$('revealClose').onclick=()=>{showOnly('hangarScreen');renderHangar()};$('upgradeShip').onclick=()=>{const cost=500*saveData.airframe;if(saveData.player.coins>=cost){saveData.player.coins-=cost;saveData.airframe++;save();renderHangar()}};$('overdriveBtn').onclick=activateOD;$('pauseBtn').onclick=()=>{if(G.mode==='play'){G.mode='pause';showOnly('pauseScreen')}};$('resumeBtn').onclick=()=>{showOnly(null);$('combatHud').classList.remove('hidden');G.mode='play';G.last=performance.now();requestAnimationFrame(loop)};$('retireBtn').onclick=()=>endMission(false);$('resultHome').onclick=()=>{showOnly('titleScreen');refreshMeta()};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));refreshMeta();draw();