'use strict';
/* GLADION v3.4 — edge-connected matte removal + cinematic combat compositing */
(()=>{
 const baseShip=window.drawShip, baseEnemy=window.drawEnemy, baseBg=window.bg;
 const paths={player:'player-gladion.png',scout:'enemy-scout.png',assault:'enemy-assault.png',shield:'enemy-shield.png',guardian:'enemy-guardian.png',boss:'boss-abyss-core.png',boss2:'boss-abyss-core-phase2.png',background:'dark-ocean.png'};
 const art={},cut={};
 const process=(key,im)=>{if(key==='background')return;try{const w=im.naturalWidth,h=im.naturalHeight,c=document.createElement('canvas');c.width=w;c.height=h;const q=c.getContext('2d',{willReadFrequently:true});q.drawImage(im,0,0);const d=q.getImageData(0,0,w,h),p=d.data,seen=new Uint8Array(w*h),queue=[];const sample=[];for(let x=0;x<w;x+=Math.max(1,Math.floor(w/24))){sample.push((x)*4,((h-1)*w+x)*4)}for(let y=0;y<h;y+=Math.max(1,Math.floor(h/24))){sample.push((y*w)*4,(y*w+w-1)*4)}let bg=[0,0,0];for(const i of sample){bg[0]+=p[i];bg[1]+=p[i+1];bg[2]+=p[i+2]}bg=bg.map(v=>v/sample.length);const metric=i=>{const dr=p[i]-bg[0],dg=p[i+1]-bg[1],db=p[i+2]-bg[2],mx=Math.max(p[i],p[i+1],p[i+2]),mn=Math.min(p[i],p[i+1],p[i+2]);return[Math.sqrt(dr*dr+dg*dg+db*db),mx-mn]};const push=(x,y)=>{if(x<0||y<0||x>=w||y>=h)return;const n=y*w+x;if(seen[n])return;const [delta,chroma]=metric(n*4);if(delta<92||(delta<132&&chroma<58)){seen[n]=1;queue.push(n)}};for(let x=0;x<w;x++){push(x,0);push(x,h-1)}for(let y=0;y<h;y++){push(0,y);push(w-1,y)}for(let hq=0;hq<queue.length;hq++){const n=queue[hq],x=n%w,y=(n/w)|0;push(x-1,y);push(x+1,y);push(x,y-1);push(x,y+1)}for(let n=0;n<w*h;n++){const i=n*4;if(seen[n]){p[i+3]=0;continue}const [delta,chroma]=metric(i);if(delta<115&&chroma<72)p[i+3]=Math.min(p[i+3],Math.max(0,Math.round((delta-72)/43*255)))}q.putImageData(d,0,0);cut[key]=c}catch(e){console.warn('sprite matte removal failed',key,e)}};
 Object.entries(paths).forEach(([k,src])=>{const im=new Image();im.decoding='async';im.onload=()=>process(k,im);im.src=src;art[k]=im});
 const ready=k=>art[k]&&art[k].complete&&art[k].naturalWidth>0,source=k=>cut[k]||art[k];
 function sprite(c,key,x,y,w,h,rot=0,flip=false,glow='#48dfff'){if(!ready(key))return false;c.save();c.translate(x,y);c.rotate(rot);if(flip)c.scale(-1,1);c.shadowColor=glow;c.shadowBlur=Math.max(12,w*.12);c.drawImage(source(key),-w/2,-h/2,w,h);c.globalCompositeOperation='lighter';c.globalAlpha=.18;c.shadowBlur=Math.max(18,w*.18);c.drawImage(source(key),-w/2,-h/2,w,h);c.restore();return true}
 function engine(c,x,y,s){c.save();c.globalCompositeOperation='lighter';for(let j=0;j<3;j++){const len=rand(48,74)*s,g=c.createLinearGradient(x-len,y,x-5*s,y);g.addColorStop(0,'rgba(20,50,255,0)');g.addColorStop(.45,'rgba(0,145,255,.32)');g.addColorStop(.78,'rgba(65,225,255,.72)');g.addColorStop(1,'rgba(255,255,255,.96)');c.globalAlpha=.45+j*.18;c.fillStyle=g;c.beginPath();c.moveTo(x-len,y);c.lineTo(x-6*s,y-(5+j*2)*s);c.lineTo(x-6*s,y+(5+j*2)*s);c.closePath();c.fill()}c.restore()}
 function aura(c,x,y,r,color){c.save();c.globalCompositeOperation='lighter';const g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(.28,color);g.addColorStop(1,'rgba(0,0,0,0)');c.globalAlpha=.22;c.fillStyle=g;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();c.restore()}
 window.drawShip=function(c,x,y,s=1){if(!ready('player'))return baseShip(c,x,y,s);aura(c,x,y,58*s,'rgba(30,180,255,.75)');engine(c,x-34*s,y,s);const pulse=1+Math.sin((G?.time||0)*10)*.016;sprite(c,'player',x,y,88*s*pulse,104*s*pulse,Math.PI/2,false,'#43dcff')};
 const map={scout:'scout',dart:'assault',armor:'guardian',bomber:'shield',drone:'assault'};
 window.drawEnemy=function(e){if(e.type==='boss'){const key=e.phase>=3&&ready('boss2')?'boss2':'boss';if(!ready(key))return baseEnemy(e);const size=Math.max(142,e.r*2.25);aura(ctx,e.x,e.y,size*.68,'rgba(255,25,90,.72)');sprite(ctx,key,e.x,e.y,size,size,Math.PI/2,true,'#ff285c');return}const key=map[e.type]||'scout';if(!ready(key))return baseEnemy(e);const size=Math.max(36,e.r*2.55);aura(ctx,e.x,e.y,size*.58,'rgba(255,35,82,.52)');sprite(ctx,key,e.x,e.y,size,size,Math.PI/2,true,'#ff365c')};
 window.bg=function(){if(!ready('background'))return baseBg();ctx.save();ctx.fillStyle='#01040b';ctx.fillRect(0,0,W,H);const im=art.background,scale=Math.max(W/im.naturalWidth,H/im.naturalHeight),dw=im.naturalWidth*scale,dh=im.naturalHeight*scale,ox=-((G.time*7)%Math.max(1,dw));ctx.globalAlpha=.96;ctx.drawImage(im,ox,0,dw,dh);ctx.drawImage(im,ox+dw,0,dw,dh);ctx.globalCompositeOperation='screen';let g=ctx.createRadialGradient(W*.58,H*.36,0,W*.58,H*.36,Math.max(W,H)*.72);g.addColorStop(0,'rgba(94,30,210,.18)');g.addColorStop(.48,'rgba(0,135,255,.09)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<24;i++){let x=(i*193-G.time*(14+i%3*4))%(W+80);if(x<0)x+=W+80;const y=(i*97)%H;ctx.globalAlpha=.18+(i%4)*.07;ctx.fillStyle='#a9e9ff';ctx.fillRect(x,y,i%5===0?2:1,i%5===0?2:1)}ctx.restore()};
 window.GLADION_ART={version:'3.4',mode:'edge-cutout-cinematic',paths,images:art,cutouts:cut};
})();
