'use strict';
/* GLADION v5.5 — single authoritative renderer */
(()=>{
const SRC={player:'./93E1037C-4420-49C7-8635-62CA31D62A7F.PNG',enemy1:'./EA3BF3FC-FEA3-41C9-B7ED-948F878B3EC7.PNG',enemy2:'./44C4AF99-9753-431D-9619-5B9DDAAECB42.PNG',enemy3:'./F773CB7A-6014-4B0B-A994-973D33536DDF.PNG',boss:'./94E02639-59FF-4E0F-8702-F88A38646A28.PNG',missile:'./CD656E5B-808B-474C-A1AA-77BB8D91FB8C.PNG',explosion:'./44355BD6-2092-4F12-9F21-286C841BCEF3.PNG',bg:'./dark-ocean.png'};
const art={};for(const[k,s]of Object.entries(SRC)){const i=new Image();i.decoding='async';i.src=s;art[k]=i}const ok=k=>art[k]?.complete&&art[k].naturalWidth;
function spr(k,x,y,h,a=1){if(!ok(k))return;const i=art[k],w=h*i.naturalWidth/i.naturalHeight;ctx.save();ctx.globalAlpha=a;ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(i,x-w/2,y-h/2,w,h);ctx.restore()}
window.drawShip=(c,x,y,s=1)=>spr('player',x,y,70*s,1);
window.drawEnemy=e=>{const k=e.type==='boss'?'boss':(e.type==='dart'||e.type==='drone')?'enemy2':(e.type==='armor'||e.type==='bomber')?'enemy3':'enemy1';spr(k,e.x,e.y,e.type==='boss'?Math.max(175,e.r*2.05):Math.max(48,e.r*3.25))};
const oldExplosion=window.explosion,blasts=[];window.explosion=(x,y,b=false)=>{oldExplosion(x,y,b);blasts.push({x,y,b,t:0,d:b?.8:.42})};
function background(){if(ok('bg')){const i=art.bg,s=Math.max(W/i.naturalWidth,H/i.naturalHeight),dw=i.naturalWidth*s,dh=i.naturalHeight*s,travel=Math.max(0,dw-W),off=travel?((G.time*7)%travel):0;ctx.drawImage(i,-off-(dw-W)/2,0,dw,dh)}else{ctx.fillStyle='#020817';ctx.fillRect(0,0,W,H)}ctx.save();ctx.globalCompositeOperation='screen';for(let n=0;n<55;n++){let x=(n*239-G.time*(11+n%4*5))%(W+50);if(x<0)x+=W+50;const y=(n*97)%H;ctx.globalAlpha=.16+(n%6)*.055;ctx.fillStyle=n%9?'#d8eeff':'#65dfff';ctx.fillRect(x,y,n%11?1:2,n%11?1:2)}ctx.restore()}
function shot(b){ctx.save();ctx.globalCompositeOperation='lighter';ctx.shadowColor=b.color||'#49dcff';ctx.shadowBlur=19;const g=ctx.createLinearGradient(b.x-34,b.y,b.x+10,b.y);g.addColorStop(0,'rgba(40,180,255,0)');g.addColorStop(.65,b.color||'#50dfff');g.addColorStop(1,'#fff');ctx.strokeStyle=g;ctx.lineWidth=Math.max(4,b.r*1.7);ctx.lineCap='round';ctx.beginPath();ctx.moveTo(b.x-34,b.y);ctx.lineTo(b.x+10,b.y);ctx.stroke();ctx.restore()}
function enemyShot(b){const a=Math.atan2(b.vy||0,b.vx||-1),boss=b.r>4,L=boss?58:38;ctx.save();ctx.translate(b.x,b.y);ctx.rotate(a);ctx.globalCompositeOperation='lighter';ctx.shadowColor=boss?'#ff174d':'#ff6b19';ctx.shadowBlur=boss?30:22;const g=ctx.createLinearGradient(-L,0,15,0);g.addColorStop(0,'rgba(255,30,0,0)');g.addColorStop(.6,boss?'#ff174d':'#ff641c');g.addColorStop(1,'#fff2c7');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(-L,0);ctx.quadraticCurveTo(-5,-8,15,0);ctx.quadraticCurveTo(-5,8,-L,0);ctx.fill();ctx.restore()}
function beam(){const x=player.x+31,y=player.y,p=1+player.laser*.09;ctx.save();ctx.globalCompositeOperation='lighter';ctx.lineCap='round';ctx.shadowColor='#00d9ff';ctx.shadowBlur=38;ctx.strokeStyle='rgba(0,170,255,.24)';ctx.lineWidth=32*p;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(W+30,y);ctx.stroke();ctx.shadowBlur=23;ctx.strokeStyle='#21dfff';ctx.lineWidth=12*p;ctx.stroke();ctx.shadowBlur=10;ctx.strokeStyle='#efffff';ctx.lineWidth=3.5*p;ctx.stroke();for(let d=x+80;d<W;d+=105){ctx.globalAlpha=.62;ctx.strokeStyle='#5feeff';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(d,y,14*p,29*p,0,0,Math.PI*2);ctx.stroke()}ctx.restore()}
const styles={SHOT:['#18caff','S'],LASER:['#c33dff','L'],MISSILE:['#ff9a20','M'],SHIELD:['#2c8fff','◆'],REPAIR:['#32e58b','+'],RAPID:['#ffd23b','»'],NOVA:['#ff3c91','N'],CORE:['#fff0a0','C']};
function drop(d){const[col,l]=styles[d.type]||['#55ddff','?'],r=17+Math.sin(G.time*8+d.x)*2;ctx.save();ctx.translate(d.x,d.y);ctx.rotate(d.spin*.5);ctx.globalCompositeOperation='lighter';ctx.shadowColor=col;ctx.shadowBlur=27;ctx.fillStyle=col+'42';ctx.strokeStyle=col;ctx.lineWidth=2.2;ctx.beginPath();for(let n=0;n<6;n++){const a=-Math.PI/2+n*Math.PI/3,x=Math.cos(a)*r,y=Math.sin(a)*r;n?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fill();ctx.stroke();ctx.rotate(-d.spin*.5);ctx.fillStyle='#fff';ctx.font='800 15px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(l,0,0);ctx.restore()}
function missile(m){spr('missile',m.x,m.y,22);ctx.save();ctx.globalCompositeOperation='lighter';ctx.strokeStyle='#ff6820';ctx.shadowColor='#ff4a10';ctx.shadowBlur=18;ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(m.x-38,m.y);ctx.lineTo(m.x-10,m.y);ctx.stroke();ctx.restore()}
window.draw=function(){ctx.save();if(G.shake)ctx.translate(rand(-G.shake,G.shake),rand(-G.shake,G.shake));background();drops.each(drop);bullets.each(shot);missiles.each(missile);enemyBullets.each(enemyShot);for(const e of enemies)drawEnemy(e);if(player.laser>0&&player.laserTick>.58-player.laser*.04)beam();/* no alpha blink: invulnerability is indicated only by shield ring */if(player.invuln>0){ctx.save();ctx.globalAlpha=.24;ctx.strokeStyle='#71eaff';ctx.shadowColor='#38dfff';ctx.shadowBlur=18;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(player.x,player.y,38,28,0,0,Math.PI*2);ctx.stroke();ctx.restore()}drawShip(ctx,player.x,player.y,.95);particles.each(p=>{ctx.save();ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.shadowColor=p.color;ctx.shadowBlur=8;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(.8,p.size*ctx.globalAlpha),0,Math.PI*2);ctx.fill();ctx.restore()});for(let i=blasts.length-1;i>=0;i--){const b=blasts[i];b.t+=1/60;if(b.t>=b.d){blasts.splice(i,1);continue}const q=b.t/b.d;spr('explosion',b.x,b.y,(b.b?250:105)*(.55+q*.8),Math.sin(Math.PI*q))}ctx.restore();if(G.flash){ctx.fillStyle=`rgba(220,248,255,${G.flash})`;ctx.fillRect(0,0,W,H)}};
window.render=window.draw;window.GLADION_RENDER_PIPELINE='5.5-single-authoritative';
})();