'use strict';
/* GLADION v3.3 — runtime matte removal + premium sprite compositing */
(()=>{
 const baseShip=window.drawShip, baseEnemy=window.drawEnemy, baseBg=window.bg;
 const paths={player:'player-gladion.png',scout:'enemy-scout.png',assault:'enemy-assault.png',shield:'enemy-shield.png',guardian:'enemy-guardian.png',boss:'boss-abyss-core.png',boss2:'boss-abyss-core-phase2.png',background:'dark-ocean.png'};
 const art={}, cut={};
 const process=(key,im)=>{if(key==='background')return;try{const w=im.naturalWidth,h=im.naturalHeight,c=document.createElement('canvas');c.width=w;c.height=h;const q=c.getContext('2d',{willReadFrequently:true});q.drawImage(im,0,0);const d=q.getImageData(0,0,w,h),p=d.data;const corners=[[2,2],[w-3,2],[2,h-3],[w-3,h-3]].map(([x,y])=>{const i=(y*w+x)*4;return[p[i],p[i+1],p[i+2]]});const bg=corners.reduce((a,v)=>a.map((n,i)=>n+v[i]/corners.length),[0,0,0]);for(let i=0;i<p.length;i+=4){const dr=p[i]-bg[0],dg=p[i+1]-bg[1],db=p[i+2]-bg[2],delta=Math.sqrt(dr*dr+dg*dg+db*db);const mx=Math.max(p[i],p[i+1],p[i+2]),mn=Math.min(p[i],p[i+1],p[i+2]);const chroma=mx-mn;let a=255;if(delta<24)a=0;else if(delta<70&&chroma<52)a=Math.round(255*(delta-24)/46);else if(mx>188&&chroma<42&&delta<145)a=Math.min(a,Math.round(255*(delta-55)/90));p[i+3]=Math.max(0,Math.min(255,a));}q.putImageData(d,0,0);cut[key]=c}catch(e){console.warn('sprite matte removal failed',key,e)}};
 Object.entries(paths).forEach(([k,src])=>{const im=new Image();im.decoding='async';im.onload=()=>process(k,im);im.src=src;art[k]=im});
 const ready=k=>art[k]&&art[k].complete&&art[k].naturalWidth>0;
 const source=k=>cut[k]||art[k];
 function sprite(c,key,x,y,w,h,rot=0,flip=false,glow='#48dfff'){if(!ready(key))return false;c.save();c.translate(x,y);c.rotate(rot);if(flip)c.scale(-1,1);c.globalCompositeOperation='source-over';c.shadowColor=glow;c.shadowBlur=Math.max(8,w*.08);c.drawImage(source(key),-w/2,-h/2,w,h);c.restore();return true}
 function engine(c,x,y,s){c.save();c.globalCompositeOperation='lighter';const len=rand(42,58)*s,g=c.createLinearGradient(x-len,y,x-8*s,y);g.addColorStop(0,'rgba(0,80,255,0)');g.addColorStop(.45,'rgba(0,170,255,.42)');g.addColorStop(.8,'rgba(90,235,255,.82)');g.addColorStop(1,'rgba(255,255,255,.96)');c.fillStyle=g;c.beginPath();c.moveTo(x-len,y);c.lineTo(x-8*s,y-7*s);c.lineTo(x-8*s,y+7*s);c.closePath();c.fill();c.restore()}
 window.drawShip=function(c,x,y,s=1){if(!ready('player'))return baseShip(c,x,y,s);engine(c,x-30*s,y,s);const pulse=1+Math.sin((G?.time||0)*10)*.018;sprite(c,'player',x,y,94*s*pulse,112*s*pulse,Math.PI/2,false,'#45dfff')};
 const map={scout:'scout',dart:'assault',armor:'guardian',bomber:'shield',drone:'assault'};
 window.drawEnemy=function(e){if(e.type==='boss'){const key=e.phase>=3&&ready('boss2')?'boss2':'boss';if(!ready(key))return baseEnemy(e);const size=Math.max(145,e.r*2.35);sprite(ctx,key,e.x,e.y,size,size,Math.PI/2,true,'#ff285c');return}const key=map[e.type]||'scout';if(!ready(key))return baseEnemy(e);const size=Math.max(38,e.r*2.7);sprite(ctx,key,e.x,e.y,size,size,Math.PI/2,true,'#ff365c')};
 window.bg=function(){if(!ready('background'))return baseBg();ctx.save();ctx.fillStyle='#01050d';ctx.fillRect(0,0,W,H);const im=art.background,scale=Math.max(W/im.naturalWidth,H/im.naturalHeight),dw=im.naturalWidth*scale,dh=im.naturalHeight*scale,travel=Math.max(1,dw),ox=-((G.time*10)%travel);ctx.globalAlpha=.94;ctx.drawImage(im,ox,0,dw,dh);ctx.drawImage(im,ox+dw,0,dw,dh);ctx.globalCompositeOperation='screen';const g=ctx.createRadialGradient(W*.58,H*.38,0,W*.58,H*.38,Math.max(W,H)*.7);g.addColorStop(0,'rgba(88,35,190,.16)');g.addColorStop(.5,'rgba(0,125,255,.08)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.restore()};
 window.GLADION_ART={version:'3.3',mode:'runtime-cutout',paths,images:art,cutouts:cut};
})();
