'use strict';
/* GLADION v5.4 — live render pipeline: cinematic background/VFX, no player blink */
(()=>{
const glow=(color,blur)=>{ctx.shadowColor=color;ctx.shadowBlur=blur};
const bgArt=new Image(); bgArt.src='./dark-ocean.png';
function fallbackShip(c,x,y,s=1){c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#e9f7ff';c.strokeStyle='#52ddff';c.lineWidth=2;c.beginPath();c.moveTo(38,0);c.lineTo(-18,-20);c.lineTo(-30,0);c.lineTo(-18,20);c.closePath();c.fill();c.stroke();c.restore()}
window.bg=function(){const t=G.time;if(bgArt.complete&&bgArt.naturalWidth){const scale=Math.max(W/bgArt.naturalWidth,H/bgArt.naturalHeight),dw=bgArt.naturalWidth*scale,dh=bgArt.naturalHeight*scale,travel=Math.max(0,dw-W);const sx=travel?-(t*10)%travel:0;ctx.drawImage(bgArt,sx-(dw-W)/2,0,dw,dh);const shade=ctx.createLinearGradient(0,0,W,0);shade.addColorStop(0,'rgba(0,8,25,.20)');shade.addColorStop(.55,'rgba(0,5,18,.03)');shade.addColorStop(1,'rgba(0,0,10,.20)');ctx.fillStyle=shade;ctx.fillRect(0,0,W,H)}else{const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#01040c');g.addColorStop(.5,'#061b43');g.addColorStop(1,'#080516');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
ctx.save();ctx.globalCompositeOperation='screen';for(let i=0;i<42;i++){const x=(i*211-t*(10+(i%3)*7))%(W+40),y=(i*83)%H,a=.18+(i%5)*.06;ctx.globalAlpha=a;ctx.fillStyle=i%7===0?'#8beaff':'#fff';ctx.fillRect(x<0?x+W+40:x,y,i%9===0?2:1,i%9===0?2:1)}ctx.restore()};
function beam(){const x=player.x+32,y=player.y,len=W-x+20,p=1+player.laser*.10,pulse=.92+.08*Math.sin(G.time*26);ctx.save();ctx.globalCompositeOperation='lighter';ctx.lineCap='round';glow('#00bfff',34);ctx.globalAlpha=.24;ctx.strokeStyle='#00a8ff';ctx.lineWidth=30*p*pulse;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(W+30,y);ctx.stroke();ctx.globalAlpha=.7;glow('#38eaff',22);ctx.strokeStyle='#24dfff';ctx.lineWidth=12*p;ctx.stroke();ctx.globalAlpha=1;glow('#dfffff',10);ctx.strokeStyle='#f4ffff';ctx.lineWidth=3.2*p;ctx.stroke();for(let d=85;d<len;d+=105){ctx.globalAlpha=.55;ctx.strokeStyle='#5feeff';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x+d,y,13*p,27*p,0,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function enemyBolt(b){const a=Math.atan2(b.vy||0,b.vx||-1),boss=(b.r||3)>4,L=boss?52:34;ctx.save();ctx.translate(b.x,b.y);ctx.rotate(a);ctx.globalCompositeOperation='lighter';glow(boss?'#ff174d':'#ff7b20',boss?28:20);const g=ctx.createLinearGradient(-L,0,14,0);g.addColorStop(0,'rgba(255,50,10,0)');g.addColorStop(.58,boss?'#ff174d':'#ff751c');g.addColorStop(1,'#fff4cf');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(-L,0);ctx.quadraticCurveTo(-6,-8,14,0);ctx.quadraticCurveTo(-6,8,-L,0);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(9,0,boss?3.8:2.7,0,Math.PI*2);ctx.fill();ctx.restore()}
const itemMap={SHOT:['#20c9ff','S'],LASER:['#bb42ff','L'],MISSILE:['#ff9c20','M'],SHIELD:['#278cff','◆'],REPAIR:['#36e68a','+'],RAPID:['#ffd23b','»'],NOVA:['#ff3d8e','N'],CORE:['#fff0a5','C']};
function item(d){const [col,label]=itemMap[d.type]||['#55ddff','?'],r=16+Math.sin(G.time*7+d.x*.01)*1.5;ctx.save();ctx.translate(d.x,d.y);ctx.globalCompositeOperation='lighter';glow(col,25);ctx.fillStyle=col+'35';ctx.strokeStyle=col;ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<6;i++){const a=-Math.PI/2+i*Math.PI/3,x=Math.cos(a)*r,y=Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fill();ctx.stroke();ctx.rotate(-d.spin);ctx.fillStyle='#fff';ctx.font='700 14px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,0,0);ctx.restore()}
function missileVfx(m){ctx.save();ctx.translate(m.x,m.y);ctx.rotate(Math.atan2(m.vy,m.vx));ctx.globalCompositeOperation='lighter';glow('#ff6a22',18);const g=ctx.createLinearGradient(-35,0,-5,0);g.addColorStop(0,'rgba(255,40,0,0)');g.addColorStop(.65,'#ff5c16');g.addColorStop(1,'#fff0a0');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(-35,0);ctx.lineTo(-5,-4);ctx.lineTo(-5,4);ctx.closePath();ctx.fill();ctx.restore()}
function aura(){if(player.invuln>0){ctx.save();ctx.globalAlpha=.25;ctx.strokeStyle='#7deeff';glow('#4ddfff',20);ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(player.x,player.y,37,27,0,0,Math.PI*2);ctx.stroke();ctx.restore()}if(player.overdrive>0){ctx.save();ctx.globalCompositeOperation='lighter';ctx.strokeStyle='#62f2ff';ctx.globalAlpha=.25;for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(player.x-rand(35,65),player.y+rand(-28,28));ctx.lineTo(player.x-rand(75,135),player.y+rand(-35,35));ctx.stroke()}ctx.restore()}}
const baseDraw=window.draw;window.draw=function(){ctx.save();if(G.shake)ctx.translate(rand(-G.shake,G.shake),rand(-G.shake,G.shake));bg();drops.each(item);bullets.each(b=>{ctx.save();ctx.globalCompositeOperation='lighter';glow(b.color||'#63e8ff',18);ctx.strokeStyle=b.color||'#63e8ff';ctx.lineWidth=Math.max(3,b.r*1.5);ctx.beginPath();ctx.moveTo(b.x-26,b.y);ctx.lineTo(b.x+8,b.y);ctx.stroke();ctx.restore()});missiles.each(missileVfx);enemyBullets.each(enemyBolt);for(const e of enemies)drawEnemy(e);aura();if(player.laser&&player.laserTick>.58-player.laser*.04)beam();
/* IMPORTANT: never blink GLADION during spawn/hit invulnerability. */
if(typeof window.drawShip==='function')window.drawShip(ctx,player.x,player.y,.95);else fallbackShip(ctx,player.x,player.y,.95);
if(player.drones){ctx.save();glow('#ffd75e',18);ctx.fillStyle='#fff2a0';ctx.beginPath();ctx.arc(player.x-3,player.y-38,6,0,Math.PI*2);ctx.fill();ctx.restore()}particles.each(p=>{ctx.save();ctx.globalAlpha=clamp(p.life/p.max,0,1);glow(p.color,8);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(.7,p.size*ctx.globalAlpha),0,Math.PI*2);ctx.fill();ctx.restore()});ctx.restore();if(G.flash){ctx.fillStyle=`rgba(220,248,255,${G.flash})`;ctx.fillRect(0,0,W,H)}};
window.GLADION_RENDER_PIPELINE='5.4-live-cinematic';
})();