import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync('index.html','utf8');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);
const gradient={addColorStop(){}};
const context=new Proxy({canvas:{},createLinearGradient:()=>gradient,createRadialGradient:()=>gradient,measureText:()=>({width:10})},{get:(o,k)=>k in o?o[k]:(typeof k==='string'?(()=>{}):undefined),set:(o,k,v)=>(o[k]=v,true)});
const elements=new Map(ids.map(id=>[id,{id,classList:{add(){},remove(){},toggle(){}},style:{},dataset:{},addEventListener(){},setPointerCapture(){},getContext:()=>context,querySelectorAll:()=>[],firstElementChild:{style:{}},get offsetWidth(){return 100}}]));
const storage=new Map([['gladion',JSON.stringify({lv:4,xp:25,coins:80,cores:7,best:900,weapon:2})]]);
const sandbox={console,Math,Date,JSON,URL,structuredClone,setTimeout,clearTimeout,setInterval,clearInterval,performance:{now:()=>0},innerWidth:844,innerHeight:390,devicePixelRatio:3,document:{getElementById:id=>elements.get(id),querySelectorAll:()=>[]},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)},navigator:{serviceWorker:{register:path=>{assert.equal(path,'./sw.js');return Promise.resolve()}}},addEventListener(){},requestAnimationFrame(){},globalThis:null};
sandbox.globalThis=sandbox;
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync('game.js','utf8'),sandbox,{filename:'game.js'});
assert.equal(elements.get('titleCores').textContent,7);
assert.equal(elements.get('titleLevel').textContent,'LV.04');
assert.ok(ids.length>=50);
assert.match(fs.readFileSync('style.css','utf8'),/env\(safe-area-inset-left/);
assert.equal(JSON.parse(fs.readFileSync('manifest.json')).orientation,'landscape');
console.log(`Runtime smoke passed with ${ids.length} resolved DOM elements at 844x390.`);
